Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Models/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using PagedList;
using System.Web.Mvc;

namespace TestMVC001.Models
{
    [Authorize(Roles = "SysAdmin,Admin")]
    public class StaffsController : Controller
    {
        private DB_95608_edukritiEntities db = new DB_95608_edukritiEntities();

        //// GET: Staffs
        //public ActionResult Index()
        //{
        //    return View(db.Staffs.ToList());
        //}

        // GET: Staffs/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffId,FirstName,MiddleName,LastName,Gender,DateOfBirth,PhoneNumber,EmailId,RFID,ORGID,Dept")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StaffId,FirstName,MiddleName,LastName,Gender,DateOfBirth,PhoneNumber,EmailId,RFID,ORGID,Dept")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ViewResult Index(string sortOrder, string currentSort, string currentFilter, string searchString, int? page)
        {
            // string currentSortOrder = currentSort;
            ViewBag.CurrentSort = sortOrder;
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            //return View(db.staffs.ToList());
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var staffs = from s in db.Staffs
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                staffs = staffs.Where(s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "FirstName":
                    if (sortOrder.Equals(currentSort))
                        staffs = staffs.OrderByDescending(s => s.FirstName);
                    else
                        staffs = staffs.OrderBy(s => s.FirstName);
                    break;
                case "LastName":
                    if (sortOrder.Equals(currentSort))
                        staffs = staffs.OrderByDescending(s => s.LastName);
                    else
                        staffs = staffs.OrderBy(s => s.LastName);
                    break;
                case "RFID":
                    if (sortOrder.Equals(currentSort))
                        staffs = staffs.OrderByDescending(s => s.RFID);
                    else
                        staffs = staffs.OrderBy(s => s.RFID);
                    break;
                default:  // Name ascending 
                    staffs = staffs.OrderBy(s => s.FirstName);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(staffs.ToPagedList(pageNumber, pageSize));
        }
    }
}

Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Newtonsoft.Json;
using TestMVC001.Core.Models;
using TestMVC001.Core.Services;
using TestMVC001.Models;

namespace TestMVC001.Controllers
{
    [Authorize(Roles = "SysAdmin,Admin,Staff")]
    public class NotificationController : Controller
    {
        // GET: Notification
        public ActionResult Index()
        {
            var groupsModel = new GroupsModel();
            return View(groupsModel);
        }

        [Route("gettree")]
        public JsonResult GetTree()
        {

            var entityItemsList = NotificationService.GetSMSTree("97005");  //TODO pass ORgID to db
            var groups = new List<Group>();
            //Convert to tree
            //Step 1: Find all parents
            foreach (var entityItem in entityItemsList)
            {
                if (entityItem.Parent == null || String.IsNullOrEmpty(entityItem.Parent))
                {
                    var group = new Group
                    {
                        Id = entityItem.Id,
                        GroupName = entityItem.Entity,
                        ChildGroups = new List<Group>()
                    };
                    groups.Add(group);
                }
            }
            entityItemsList.RemoveAll(item => item.Parent == null || String.IsNullOrEmpty(item.Parent));
            FindParent(entityItemsList, ref groups);
            return new JsonResult { Data = groups, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [Route("sendnotification")]
        public ContentResult SendNotification(NotificationModel model)
        {
            string connectionString = WebConfigurationManager.ConnectionStrings["myConnectionString"].ToString();
            const string notificationSender = "School Admin";
            const string notificationCategory = "Test";
            using (var con = new SqlConnection(connectionString))
            {
                con.Open();
                string query = "INSERT INTO [dbo].[tblNotification] ([PhoneNumber],[Sender],[Message],[Category]) VALUES('" + model.ToPhoneNumber + "', '" + notificationSender + "',  '" + model.Message + "',   '" + notificationCategory + "') ";
                var cmd = new SqlCommand(query, con);
                cmd.ExecuteNonQuery();
                con.Close();
            }
            var smsResponseModel = SendSmsService.SendNotification(model.ToPhoneNumber, model.Message);
            AttendanceService.InsertSmsResponse(smsResponseModel);
            //return new JsonResult { Data = smsResponseModel, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

            if (smsResponseModel.Status == "Success")
            {
                return Content("Message Sent!");
            }
            else
            {
                return Content(smsResponseModel.Status);
            }
        }

        [Route("notification/getphonenumbers"), HttpGet]
        public JsonResult GetPhoneNumbers(List<string> groupIdsList)
        {
            var phoneNumbers = NotificationService.GetPhoneNumbers(groupIdsList, "97005");  //TODO pass ORgID to db
            return new JsonResult { Data = phoneNumbers, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        
        public void FindParent(List<EntityItem> entityItemsList, ref List<Group> groups)
        {
            //Step 2: Find all children for each parent
            while (entityItemsList.Count > 0)
            {
                var itemsToRemove = new List<EntityItem>();
                foreach (var entityItem in entityItemsList)
                {
                    var group = new Group
                    {
                        Id = entityItem.Id,
                        GroupName = entityItem.Entity,
                        ChildGroups = new List<Group>()
                    };
                    foreach (var parent in groups)
                    {
                        if (entityItem.Parent == parent.Id)
                        {
                            parent.ChildGroups.Add(group);
                            itemsToRemove.Add(entityItem);
                        }
                        else
                        {
                            if (parent.ChildGroups.Count > 0)
                            {
                                foreach (var child in parent.ChildGroups)
                                {
                                    if (child.Id == entityItem.Parent)
                                    {
                                        child.ChildGroups.Add(group);
                                        itemsToRemove.Add(entityItem);
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
                entityItemsList.RemoveAll(itemsToRemove.Contains);
            }
        }
    }

    public class Group
    {
        public string Id;
        public string GroupName;
        public List<Group> ChildGroups;
    }
}

Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestMVC001.Core.Models;
using TestMVC001.Core.Services;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace TestMVC001.Controllers
{
    [Authorize(Roles = "SysAdmin,Admin,Staff,Student")]
    public class ReportController : Controller
    {
        public ActionResult Student()
        {
            return View();
        }
        public ActionResult Staff()
        {
            return View();
        }
       
        [Route("getreport")]
        public JsonResult GetReport(ReportRequestModel reportRequestModel)
        {
            var reportResponseModel = ReportService.GetAttendanceReport(reportRequestModel);

            //TODO pass ORgID to db
            var sessionUserName = User.Identity.GetUserName();
            var filteredRows = new List<Row>();
            if (User.IsInRole("Student") || ((User.IsInRole("Staff") && reportRequestModel.Category == "Staff")))
            {                
                //List<Row> filteredRows = (from row in reportResponseModel.Rows let rowUserName = row.RowCells[row.RowCells.Count - 1] where !String.IsNullOrEmpty(rowUserName) && !String.IsNullOrEmpty(sessionUserName) && (rowUserName.ToLower() == sessionUserName.ToLower()) select row).ToList();
                foreach (var row in reportResponseModel.Rows)
                {
                    var rowUserName = row.RowCells[row.RowCells.Count - 1];
                    if (!String.IsNullOrEmpty(rowUserName) && !String.IsNullOrEmpty(sessionUserName) && (rowUserName.ToLower() == sessionUserName.ToLower()))
                    {
                        filteredRows.Add(row);
                    }
                }
                reportResponseModel.Rows = filteredRows;
            }
            return new JsonResult { Data = reportResponseModel, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        
	}
}

Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace TestMVC001.Controllers
{
    public class WelcomeController : Controller
    {
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{
    var isAdmin = User.IsInRole("Admin");
    var isStaff = User.IsInRole("Staff");
    var isStudent = User.IsInRole("Student");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Edukriti - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!--Below Line added by Shailesh-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.table2excel.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Attendance/Report.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/css3-mediaqueries.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.fancytree.js")"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/Styles/CommonStyles.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/normalize.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/datepicker.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/fancytree.css")" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Content/Fonts/Montserrat-Black.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-Bold.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-ExtraBold.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-Hairline.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-Light.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-Regular.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-SemiBold.otf")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Fonts/Montserrat-UltraLight.otf")" rel="stylesheet" type="text/css" />*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle mobile" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(".", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><span class="glyphicon glyphicon-home"></span>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        if (isAdmin || isStaff)
                        {
                            <li class="dropdown"><span class="glyphicon glyphicon-th-list"></span>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Reports
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Student", "Student", "Report")</li>
                                    <li>@Html.ActionLink("Staff", "Staff", "Report")</li>
                                </ul>
                            </li>
                        }
                        else if (isStudent)
                        {
                            <li><span class="glyphicon glyphicon-th-list"></span>@Html.ActionLink("Reports", "Student", "Report")</li>
                        }
                        if (isAdmin)
                        {
                            <li class="dropdown"><span class="glyphicon glyphicon-pencil"></span>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Manage
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Students", "Index", "Students")</li>
                                    <li>@Html.ActionLink("Staff", "Index", "Staffs")</li>
                                </ul>
                            </li>
                        }
                        if (isAdmin || isStaff)
                        {
                            <li><span class="glyphicon glyphicon-envelope"></span>@Html.ActionLink("Send SMS", "Index", "Notification")</li>
                        }
                    }
                    <li><span class="glyphicon glyphicon-phone-alt"></span>@Html.ActionLink("Contact Us", "Contact", "Welcome")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.MvcSiteMap().SiteMapPath()
        @RenderBody()
        
    </div>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year Edukriti. All rights reserved.</p>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>

Edukriti_V1(Nov1)/TestMVC001/TestMVC001/Views/Shared/_ReportDataPartial.cshtml
@using TestMVC001.Core.Models;
@model TestMVC001.Core.Models.ReportResponseModel

<h2>This is report data</h2>
@if (Model.DataTable != null && Model.DataTable.Rows.Count > 0)
{
    <table>
        <thead>
        <tr>
            @foreach (var column in Model.DataTable.Columns)
            {
                @*<td>@column</td>*@
            }
        </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.DataTable.Rows)
            {
                <tr>
                    @*@foreach (var dataCol in @row)
                    {
                        <td>@dataCol</td>
                    }*@
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>There is no data for the selected criteria.</h3>
}